name: Auto Assign on /startwork

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign-and-label:
    if: startsWith(github.event.comment.body, '/startwork')
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue author and add labels
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const commentBody = context.payload.comment.body;

            // Extract level from comment (default to 2 if not specified)
            const match = commentBody.match(/^\/startwork\s*(\d)?/i);
            const level = match && match[1] ? match[1] : '2'; // default Level-2
            const levelLabel = `Level-${level}`;

            // Get issue to find the author
            const issue = await github.rest.issues.get({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber
            });

            const issueAuthor = issue.data.user.login;

            // Check permission (optional)
            try {
              const permission = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: repoOwner,
                repo: repoName,
                username: issueAuthor
              });

              const userPermission = permission.data.permission;
              const allowedPermissions = ['admin', 'maintain', 'write'];

              if (!allowedPermissions.includes(userPermission)) {
                console.log(`User @${issueAuthor} is not a collaborator. Permission: ${userPermission}`);
                return;
              }

              // Assign issue to author
              await github.rest.issues.addAssignees({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                assignees: [issueAuthor]
              });

              // Add labels
              await github.rest.issues.addLabels({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                labels: [levelLabel, "GsSOC", "Start Working"]
              });

              console.log(`Assigned issue #${issueNumber} to @${issueAuthor} with label ${levelLabel}.`);

            } catch (error) {
              console.error(`Failed to process /startwork:`, error);
            }
